-- MySQL Script generated by MySQL Workbench
-- jeu. 05 mai 2016 12:29:37 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bluepurse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bluepurse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bluepurse` DEFAULT CHARACTER SET latin1 ;
USE `bluepurse` ;

-- -----------------------------------------------------
-- Table `bluepurse`.`param_usergroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bluepurse`.`param_usergroup` ;

CREATE TABLE IF NOT EXISTS `bluepurse`.`param_usergroup` (
  `code` INT(11) NOT NULL,
  `label` VARCHAR(30) NOT NULL,
  `level` TINYINT(4) NOT NULL,
  `inddefaul` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bluepurse`.`param_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bluepurse`.`param_status` ;

CREATE TABLE IF NOT EXISTS `bluepurse`.`param_status` (
  `code` INT(11) NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(30) NOT NULL,
  `inddefaul` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`code`),
  UNIQUE INDEX `status_label_unique` (`label` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bluepurse`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bluepurse`.`user` ;

CREATE TABLE IF NOT EXISTS `bluepurse`.`user` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `firstname` VARCHAR(50) NULL,
  `lastname` VARCHAR(50) NULL,
  `usergroup` INT(11) NOT NULL DEFAULT '1',
  `status` INT(11) NOT NULL DEFAULT '2',
  `subscriptiondate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `unsubscriptiondate` DATETIME NULL DEFAULT NULL,
  `lastModificationDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_email_unique` (`email` ASC),
  INDEX `fk_user_usergroup_idx` (`usergroup` ASC),
  INDEX `fk_user_status_idx` (`status` ASC),
  CONSTRAINT `fk_user_usergroup`
    FOREIGN KEY (`usergroup`)
    REFERENCES `bluepurse`.`param_usergroup` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_status`
    FOREIGN KEY (`status`)
    REFERENCES `bluepurse`.`param_status` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bluepurse`.`param_recurrency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bluepurse`.`param_recurrency` ;

CREATE TABLE IF NOT EXISTS `bluepurse`.`param_recurrency` (
  `code` INT(11) UNSIGNED NOT NULL,
  `label` VARCHAR(30) NOT NULL,
  `inddefaul` TINYINT(1) NOT NULL DEFAULT '0',
  INDEX `id_2` (),
  PRIMARY KEY (`code`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bluepurse`.`param_buckettype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bluepurse`.`param_buckettype` ;

CREATE TABLE IF NOT EXISTS `bluepurse`.`param_buckettype` (
  `code` INT(11) UNSIGNED NOT NULL,
  `label` VARCHAR(200) NULL,
  `inddefaul` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bluepurse`.`bucket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bluepurse`.`bucket` ;

CREATE TABLE IF NOT EXISTS `bluepurse`.`bucket` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(30) NOT NULL,
  `user` INT(11) UNSIGNED NOT NULL,
  `inddefaul` TINYINT(1) NOT NULL DEFAULT '0',
  `type` INT(11) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC),
  INDEX `id_2` (`id` ASC),
  INDEX `fk_bucket_user_idx` (`user` ASC),
  INDEX `fk_bucket_type_idx` (`type` ASC),
  CONSTRAINT `fk_bucket_user`
    FOREIGN KEY (`user`)
    REFERENCES `bluepurse`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bucket_type`
    FOREIGN KEY (`type`)
    REFERENCES `bluepurse`.`param_buckettype` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bluepurse`.`purse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bluepurse`.`purse` ;

CREATE TABLE IF NOT EXISTS `bluepurse`.`purse` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `user` INT(11) UNSIGNED NOT NULL,
  `creationdate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `closedate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bluepurse`.`bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bluepurse`.`bill` ;

CREATE TABLE IF NOT EXISTS `bluepurse`.`bill` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  --`out` BIGINT UNSIGNED NOT NULL,
  `label` VARCHAR(200) NULL,
  `user` INT(11) UNSIGNED NOT NULL,
  `object` BLOB NOT NULL,
  `creationdate` DATETIME NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  `deletiondate` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bill_user_idx` (`user` ASC),
  --CONSTRAINT `fk_bill_out`
    --FOREIGN KEY ()
    --REFERENCES `bluepurse`.`out` (`id`)
    --ON DELETE NO ACTION
    --ON UPDATE NO ACTION,
  CONSTRAINT `fk_bill_user`
    FOREIGN KEY (`user`)
    REFERENCES `bluepurse`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bluepurse`.`out`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bluepurse`.`out` ;

CREATE TABLE IF NOT EXISTS `bluepurse`.`out` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,3) NOT NULL,
  `user` INT(11) UNSIGNED NOT NULL,
  `label` VARCHAR(50) NULL DEFAULT 'undefined',
  `recurrency` INT(11) UNSIGNED NOT NULL DEFAULT '1',
  `bucket` INT(11) UNSIGNED NULL DEFAULT '1',
  `purse` INT(11) UNSIGNED NOT NULL,
  `creationdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedate` DATETIME NULL DEFAULT NULL,
  `deletedate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC),
  INDEX `id_2` (`id` ASC),
  INDEX `fk_out_user_idx` (`user` ASC),
  INDEX `fk_out_recurrency_idx` (`recurrency` ASC),
  INDEX `fk_out_purse_idx` (`purse` ASC),
  CONSTRAINT `fk_out_user`
    FOREIGN KEY (`user`)
    REFERENCES `bluepurse`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_out_recurrency`
    FOREIGN KEY (`recurrency`)
    REFERENCES `bluepurse`.`param_recurrency` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_out_bucket`
    FOREIGN KEY ()
    REFERENCES `bluepurse`.`bucket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_out_purse`
    FOREIGN KEY (`purse`)
    REFERENCES `bluepurse`.`purse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bluepurse`.`contribution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bluepurse`.`contribution` ;

CREATE TABLE IF NOT EXISTS `bluepurse`.`contribution` (
  `user` INT(11) NOT NULL,
  `purse` INT(11) NOT NULL,
  INDEX `fk_contribution_purse_idx` (`purse` ASC),
  INDEX `fk_contribution_user_idx` (`user` ASC),
  CONSTRAINT `fk_contribution_purse`
    FOREIGN KEY (`purse`)
    REFERENCES `bluepurse`.`purse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contribution_user`
    FOREIGN KEY (`user`)
    REFERENCES `bluepurse`.`user` (`usergroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bluepurse`.`param_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bluepurse`.`param_info` ;

CREATE TABLE IF NOT EXISTS `bluepurse`.`param_info` (
  `code` VARCHAR(10) NOT NULL,
  `value` VARCHAR(20) NOT NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bluepurse`.`in`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bluepurse`.`in` ;

CREATE TABLE IF NOT EXISTS `bluepurse`.`in` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,3) NOT NULL,
  `user` INT(11) UNSIGNED NOT NULL,
  `label` VARCHAR(50) NULL DEFAULT 'undefined',
  `recurrency` INT(11) UNSIGNED NOT NULL DEFAULT '1',
  `bucket` INT(11) UNSIGNED NULL DEFAULT '1',
  `purse` INT(11) UNSIGNED NOT NULL,
  `creationdate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedate` DATETIME NULL DEFAULT NULL,
  `deletedate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id` (`id` ASC),
  INDEX `id_2` (`id` ASC),
  INDEX `fk_in_user_idx` (`user` ASC),
  INDEX `fk_in_recurrency_idx` (`recurrency` ASC),
  INDEX `fk_in_purse_idx` (`purse` ASC),
  CONSTRAINT `fk_in_user`
    FOREIGN KEY (`user`)
    REFERENCES `bluepurse`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_in_recurrency`
    FOREIGN KEY (`recurrency`)
    REFERENCES `bluepurse`.`param_recurrency` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_in_bucket`
    FOREIGN KEY ()
    REFERENCES `bluepurse`.`bucket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_in_purse`
    FOREIGN KEY (`purse`)
    REFERENCES `bluepurse`.`purse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
